platform:
  - x64

environment:
  global:
    PYTHON: 'C:\Python37-x64'

install:
  - set
  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"

build: off

test_script:
  # pyinstaller 3.5 doesn't work with pyqt 5.12.3, see:
  # https://github.com/pyinstaller/pyinstaller/issues/4293
  - pip install pyqt5==5.12.2
  - pip install -e .
  - pip install flake8 pyinstaller
  - flake8
  - pyinstaller steam-acolyte.spec
  - move dist\steam-acolyte.exe dist\acolyte-%APPVEYOR_REPO_TAG_NAME%.exe

artifacts:
  - path: dist/acolyte-*.exe

deploy:
  provider: GitHub
  artifact: /acolyte-.*\.exe/
  auth_token:
    secure: Y046OI+Lf52sMlPE1pHFw+JUbqJoVsuHtMxcCC3E/vggOgaaFO3x702Urn9DqyZM
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
    PLATFORM: x64
