platform:
  - x64

environment:
  global:
    PYTHON: 'C:\Python37-x64'

install:
  - set
  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"

build: off

test_script:
  - pip install -e .
  - pip install flake8 pyinstaller
  - flake8
  - python -m PyInstaller
        --windowed --onefile
        --name acolyte-%APPVEYOR_REPO_TAG_NAME%
        steam_acolyte.py

artifacts:
  - path: dist/acolyte-*.exe

deploy:
  provider: GitHub
  artifact: /acolyte-.*\.exe/
  auth_token:
    secure: Y046OI+Lf52sMlPE1pHFw+JUbqJoVsuHtMxcCC3E/vggOgaaFO3x702Urn9DqyZM
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
    PLATFORM: x64
