platform:
  - x64

environment:
  global:
    PYTHON: 'C:\Python37-x64'

install:
  - set
  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"

build: off

test_script:
  - pip install pyqt5
  - pip install -e .
  - pip install flake8 pyinstaller
  - flake8

  # Create single file EXE redistributable:
  - choco install -y imagemagick
  - refreshenv
  - set "PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%"
  - magick -background none steam_acolyte/acolyte.svg -resize 16x16 _16.ico
  - magick -background none steam_acolyte/acolyte.svg -resize 32x32 _32.ico
  - magick -background none steam_acolyte/acolyte.svg -resize 48x48 _48.ico
  - magick -background none steam_acolyte/acolyte.svg -resize 64x64 _64.ico
  - magick -background none steam_acolyte/acolyte.svg -resize 128x128 _128.ico
  - magick -background none steam_acolyte/acolyte.svg -resize 256x256 _256.ico
  - magick -background none _16.ico _32.ico _48.ico _64.ico _128.ico _256.ico acolyte.ico
  - pyinstaller steam-acolyte.spec
  - move dist\steam-acolyte.exe dist\acolyte-%APPVEYOR_REPO_TAG_NAME%.exe

artifacts:
  - path: dist/acolyte-*.exe

deploy:
  provider: GitHub
  artifact: /acolyte-.*\.exe/
  auth_token:
    secure: Y046OI+Lf52sMlPE1pHFw+JUbqJoVsuHtMxcCC3E/vggOgaaFO3x702Urn9DqyZM
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
    PLATFORM: x64
