language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - python setup.py sdist bdist_wheel
  # Need new pip versions to deal with recent manylinux wheels. At the time of
  # writing, PyQt5 is released as manylinux2014 whl which requires pip 19.3:
  - pip install --upgrade pip
  - pip install dist/*.whl
  - pip install flake8 twine

script:
  - twine check dist/*
  - flake8

jobs:
  include:
    - stage: deploy
      name: Upload release to PyPI
      if: tag is present
      script: twine upload dist/*.tar.gz dist/*.whl
      env:
        - TWINE_USERNAME=coldfix-deploy
        # TWINE_PASSWORD:
        - secure: "iHDI7WecipaFIKVKfPRU+0aMi7kYIqqP1Cvb4KGYXa31+O003TMhIdAgsLyUbn0zpUTorD9QkovE8CEWJrtrq/PEqqFdmss6DuOX17/P5Nl1+IkHk848Xm19aIFeGJQNIlICvO4DOVAd/LgRkeWKq6X/upnoF4YaxsVmIhueabzRwwHbSRbJlNDIrVSlxAgHoehboZXmRaWP/NUVlmN4+TeAy4sIr/jbjNNoEU5pDudWXPa9evJ1KtLIu6HLiFeS3K0U8woeSjjMAH0IZ58oADr+vCF3W3QSLj3a9+QStxAduXaHeaGpWUM9bJB96T+UVGGisn/rhB6jBlrE0cWKSflwh+SdEUL8iaKIM/ELcZ8qX9oYtemVu0SkwgGsP+RuMRFT7W7I4TuVHvdWAeeXcKoi1Y/5pC81nc4btYwve5JtKvaKxrW5/6yjfoL7nGquXjRs0G7hkVYvSSfUxJylAbLnr4YKAB78223hBO1sxRjBXxgJak+YRtHsScYRPpjvmxYGvfTF5q4jlXVKPgbdpKz1HFudj5sI+fKhGfXDKu7vMOizWOLNZoV/XQi9VUOS70UF5DCPA4UBUWod+v4W5pSULGy15MSAAVZ5jq3uBhUKM0cphd8p6jQEfzYgsbGUYB38+pRD4zxpbYoQKmJgKC2zg9E/uDXlNlsySazJhq8="
