name: Python Package
on:
  push:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python:
          - "3.5"
          - "3.6"
          - "3.7"
          - "3.8"
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - run: python -m pip install -U pip
      - run: python -m pip install setuptools wheel
      - run: python -m pip install flake8 twine

      - run: python setup.py sdist bdist_wheel
      - run: python -m pip install dist/*.whl
      - run: twine check dist/*
      - run: flake8

      - name: Extract release info
        id: release
        run: |
          echo "::set-output name=tagname::${GITHUB_REF##*/}"
          echo "::set-output name=md5sum::$(md5sum dist/*.tar.gz | cut -d' ' -f1)"

      - name: Generate PKGBUILD
        run: |
          sed .github/PKGBUILD >dist/PKGBUILD \
            -e "s/{{VERSION}}/${{ steps.release.outputs.tagname }}/" \
            -e "s/{{MD5SUM}}/${{ steps.release.outputs.md5sum }}/"
          cat dist/PKGBUILD

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
        if: startsWith(github.ref, 'refs/tags/v') &&
            matrix.os == 'ubuntu-latest' &&
            matrix.python == '3.8'

  deploy:
    name: Upload release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v') && success()

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install twine

      - name: Extract release info
        id: release
        run: echo "::set-output name=tagname::${GITHUB_REF##*/}"

      - name: Publish PyPI package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload dist/*.whl dist/*.tar.gz

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: steam-acolyte
          pkgbuild: dist/PKGBUILD
          commit_message: Update to ${{ steps.release.outputs.tagname }}
          commit_username: acolyte
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
